Update build-ipa.yml

diff --git a/.github/workflows/build-ipa.yml b/.github/workflows/build-ipa.yml
--- a/.github/workflows/build-ipa.yml
+++ b/.github/workflows/build-ipa.yml
@@ -399,7 +399,21 @@ jobs:
 
           echo "=== Build win32u unix ==="
           chmod +x build/win32u-unix/build.sh
-          ./build/win32u-unix/build.sh
+          
+                    echo "=== Build ntdll unix ==="
+          chmod +x build/ntdll-unix/build.sh
+
+          set +e
+          ./build/ntdll-unix/build.sh
+          ntdll_status=$?
+          set -e
+
+          echo "=== dwrite_unixlib compiler error ==="
+          cat build/ntdll-unix/obj/dwrite_unixlib.err || true
+
+          if [ "$ntdll_status" -ne 0 ]; then
+            exit "$ntdll_status"
+          fi
 
           echo "=== Verify Wine libs ==="
 
